-- MySQL Script generated by MySQL Workbench
-- Fri Mar 17 23:42:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema session
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema session
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `session` DEFAULT CHARACTER SET utf8 ;
USE `session` ;

-- -----------------------------------------------------
-- Table `session`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `session`.`task` (
  `task_id` INT NOT NULL,
  `task_name` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `start_time` DATETIME NULL,
  `finish_time` DATETIME NULL,
  `task_type` VARCHAR(45) NULL,
  `task_status` VARCHAR(45) NULL,
  `task_param` JSON NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
